<a href="https://colab.research.google.com/github/marquesgabi/metodos_numericos/blob/master/Aula_04_Met_Matematicos_set_01_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[0.9 ,0.3 ,0.1] ,[0.1 ,0.5 ,0.2] , [0.0 ,0.2 ,0.7]])
b = np.array([30.0 ,25.0 ,10.0])

In [3]:
# "Never invert a matrix explicitly unless your life depends on it..."
#Ax=b-------> x=inv(A)*b
y = np.linalg.inv(A) #calcula a inversa da matriz A
sol = np.dot(y,b) #produto de matriz invA pela b
print(sol)

[17.88461538 45.96153846  1.15384615]


In [4]:
w = np.linalg.pinv(A)
sol = np.dot(w,b)
print(sol)

[17.88461538 45.96153846  1.15384615]


In [5]:
# https://mathworld.wolfram.com/Moore-PenroseMatrixInverse.html

In [6]:
print(A)

[[0.9 0.3 0.1]
 [0.1 0.5 0.2]
 [0.  0.2 0.7]]


In [7]:
print(A[:,1]) #imprime a segunda coluna da matriz pq a primeira e a coluna 0

[0.3 0.5 0.2]


In [8]:
print(A[1,:]) #imprime a segunda linha, pq a primeira e a linha 0 e todas as colunas

[0.1 0.5 0.2]


In [9]:
print(A[:,-1]) # imprime todas as linhas e a ultima coluna

[0.1 0.2 0.7]


In [10]:
print(A[:,:-1]) #todas as linhas exceto a ultima coluna

[[0.9 0.3]
 [0.1 0.5]
 [0.  0.2]]
