<a href="https://colab.research.google.com/github/marquesgabi/metodos_matematicos/blob/master/Aula_01_Met_Matematicos_ago_18_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# testando primeiros
print('Hello world')
print('Hello world, I am evolving')

Hello world
Hello world, I am evolving


$x=\frac{a}{b}$

In [ ]:
for k in range(2):
  for i in range(2):
    for j in range(2):
      print('k=',k,'i=',i,'j=',j)

k= 0 i= 0 j= 0
k= 0 i= 0 j= 1
k= 0 i= 1 j= 0
k= 0 i= 1 j= 1
k= 1 i= 0 j= 0
k= 1 i= 0 j= 1
k= 1 i= 1 j= 0
k= 1 i= 1 j= 1


In [ ]:
for k in range(2):
  for i in range(2):
    for j in range(2):
      print('k=',k,'i=',i,'j=',j)
  print('===================')

k= 0 i= 0 j= 0
k= 0 i= 0 j= 1
k= 0 i= 1 j= 0
k= 0 i= 1 j= 1
k= 1 i= 0 j= 0
k= 1 i= 0 j= 1
k= 1 i= 1 j= 0
k= 1 i= 1 j= 1


In [ ]:
x=[] # lista exemplo
for i in range(5):
  x.append(i)
print(x)

[0, 1, 2, 3, 4]


In [ ]:
x=[] # lista exemplo
w=[]
for i in range(3):
  for j in range(3):
    x.append(j)
  w.append(x)
print(w)

[[0, 1, 2, 0, 1, 2, 0, 1, 2], [0, 1, 2, 0, 1, 2, 0, 1, 2], [0, 1, 2, 0, 1, 2, 0, 1, 2]]


In [ ]:
 # lista exemplo
y=[]
for i in range(3):
  x=[]
  for j in range(3):
    x.append(j)
  y.append(x)
print(y)

[[0, 1, 2], [0, 1, 2], [0, 1, 2]]


In [ ]:
print(y)

[[0, 1, 2], [0, 1, 2], [0, 1, 2]]


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.DataFrame(y)
print(df)

   0  1  2
0  0  1  2
1  0  1  2
2  0  1  2


In [ ]:
mat=np.array(y)
print(mat)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [ ]:
mat[0,1]=99
print(mat)

[[ 0 99  2]
 [ 0  1  2]
 [ 0  1  2]]


In [ ]:
print(mat[0,:])

[ 0 99  2]


In [ ]:
print(mat[:,0])

[0 0 0]


In [ ]:
# Recaptulando
# 1-tem o formato lista
# 2-tem o formato numpy array
# 3- tem o formato dataframe
# 4- indice começa no zero
# 5- tem varias situações que é possível converter formato